# Generated by Django 2.2.3 on 2019-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_auto_20190718_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Email',
            field=models.EmailField(blank=True, default='example@mail.com', max_length=50),
        ),
    ]
