# Generated by Django 2.2.3 on 2019-07-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='image',
        ),
    ]
