# Generated by Django 2.2.3 on 2019-08-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_post_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PythonCourse',
            new_name='PythonBasicCourse',
        ),
    ]
