# Generated by Django 2.2.3 on 2019-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_auto_20190806_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonbasiccourse',
            name='teacher',
            field=models.CharField(default='Erfan Esmaeeli', max_length=80, null=True),
        ),
    ]
