# Generated by Django 2.2.3 on 2019-08-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_pythonbasiccourse_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythonbasiccourse',
            old_name='teacher',
            new_name='Teacher',
        ),
    ]
