# Generated by Django 2.2.3 on 2019-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_auto_20190806_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythonbasiccourse',
            name='Title',
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pythonbasiccourse',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
